title: Rahul Kumar # your name (or website title) here
logo: "/images/img.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Welcome to Rahul's portfolio.
  <br><br>
  I'm a Data Scientist/Analyst, currently working as a researcher in the Social Neuroscience and Games (SNaG) Lab at the University of Colorado Boulder.
  <br><br>
  Skilled in machine learning, neural network ablation and statistical analysis with an extensive background in analyzing large datasets. 
  <br><br>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
