title: Rahul Mohan Kumar # your name (or website title) here
logo: "/images/img.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Rahul is a Data Scientist currently working as a researcher in the Social Neuroscience and Games (SNaG) Lab at the University of Colorado Boulder.
  <br><br>
  Skilled in all steps of machine learning engineering, Rahul enjoys building intelligent systems for better customer experiences and informed business decisions.
  <br><br>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
